runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: mixmind_application.app

skip_files:
- google-cloud-sdk/
- venv/
- ^(.*/)?.*\.sw[po]$

libraries:
- name: ssl
  version: latest
